### ISSUE TITLE
Feature request: app.exception_handler does not work when used in separate file

### ISSUE THREAD

**Issue by heitorlessa** [aws-powertools/powertools-lambda-python#1193]
### Discussed in https://github.com/awslabs/aws-lambda-powertools-python/discussions/1191

<div type='discussions-op-text'>

<sup>Originally posted by **arunbhati** April 29, 2022</sup>
Hi, 

I am using **APIGatewayRestResolver** and I'm having trouble working with **@app.exception_handler**. When I have **APIGatewayRestResolver** object and **@app.exception_handler** decorator in same file then it works but if I create a separate file for exceptions(**exceptions.py**) and do the import of APIGatewayRestResolver then it doesn't work. 
Following are steps to reproduce.
1. Create a lambda function in Python with Lambda Layer for AWS Powertools from [here](https://awslabs.github.io/aws-lambda-powertools-python/latest/).
2. Attach this Zip file to lambda function - Zip file: [Archive.zip](https://github.com/awslabs/aws-lambda-powertools-python/files/8587999/Archive.zip)
3. Use following input for Lambda request
```
{
  "resource": "/proxy",
  "path": "/proxy",
  "httpMethod": "GET",
  "headers": null
}
```
4. Lambda function should fail with following error
```
{
  "errorMessage": "",
  "errorType": "ValueError",
  "requestId": "24f06853-16fc-4657-9360-40409f0726be",
  "stackTrace": [
    "  File \"/var/task/lambda_function.py\", line 10, in lambda_handler\n    return axis_controllers.main(event, context)\n",
    "  File \"/var/task/src/abc/axis_controllers.py\", line 11, in main\n    return app.resolve(event, context)\n",
    "  File \"/opt/python/aws_lambda_powertools/event_handler/api_gateway.py\", line 498, in resolve\n    return self._resolve().build(self.current_event, self._cors)\n",
```
5. Now move **ValueError** exception method from **exceptions.py** into **__init__.py** file in same folder.
6. Rerun test with same input and now lambda output will show expected result(shown below).
7.
```
{
  "statusCode": 400,
  "headers": {
    "Content-Type": "text/plain"
  },
  "body": "Invalid request",
  "isBase64Encoded": false
}
```

I don't have much expertise on how decorator works so any help here would be appreciated.
Thanks.</div>

**Comment by heitorlessa** [comment]
hey @arunbhati thanks for sending over an archive to help reproduce it quickly! The issue is that `exceptions.py` code is never executed, because it isn't being imported anywhere else.

To confirm it, I've added a dummy constant within `exceptions.py` and imported it from your `lambda_function.py`. I'm gonna close this and create a feature request to support defining exception handlers within in separate files via [`Router`](https://awslabs.github.io/aws-lambda-powertools-python/latest/core/event_handler/api_gateway/#split-routes-with-router) instances - this will make the  process more easily in the future (after our pause).

**lambda_function.py**

```python
import src.abc.axis_controllers as axis_controllers
from src.abc.exceptions import HELLO   # HERE!

def lambda_handler(event, context):

    return axis_controllers.main(event, context)



event = {
  "resource": "/proxy",
  "path": "/proxy",
  "httpMethod": "GET",
  "headers": ""
}

print(HELLO)
lambda_handler(event, {})

```

**exceptions.py**

```python
from aws_lambda_powertools.event_handler import content_types
from aws_lambda_powertools.event_handler.api_gateway import Response
from aws_lambda_powertools.event_handler.exceptions import NotFoundError

from src.abc import app

HELLO = "WORLD"

@app.exception_handler(ValueError)
def handle_value_error(ex: ValueError):
    metadata = {"path": app.current_event.path}
    print(f"Malformed request: {metadata}")

    return Response(
        status_code=400,
        content_type=content_types.TEXT_PLAIN,
        body="Invalid request",
    )


@app.not_found
def handle_not_found_errors(exc: NotFoundError) -> Response:
    # Return 418 upon 404 errors
    print(f"Not found route: {app.current_event.path}")
    return Response(
        status_code=418,
        content_type=content_types.TEXT_PLAIN,
        body="I'm a teapot!"
    )
```

**Comment by jasmarc** [comment]
> I'm gonna close this and create a feature request to support defining exception handlers within in separate files via [`Router`](https://awslabs.github.io/aws-lambda-powertools-python/latest/core/event_handler/api_gateway/#split-routes-with-router) instances - this will make the process more easily in the future (after our pause).

Hi @heitorlessa did you actually create this feature request? I'm having trouble finding it. Was it every implemented, if so?

**Comment by heitorlessa** [comment]
Hey @jasmarc yeah, sorry I didn't update this back (my bad) - it's already live: https://awslabs.github.io/aws-lambda-powertools-python/2.7.1/core/event_handler/api_gateway/#specialized-router-types

* **PR**: https://github.com/awslabs/aws-lambda-powertools-python/pull/1824

**Comment by SzymonSwic** [comment]
Hi @heitorlessa, has this issue been solved with the mentioned PR: https://github.com/aws-powertools/powertools-lambda-python/pull/1824? With newest version of powertools (2.25.0) I am not able to define exception handlers in a separate file with Router. Is there some other way to achieve it?

**Comment by rajalokan** [comment]
Agree to SzymonSwic. I can confirm separate routes using (`router`) works. However, I'm still unsure how to split the exceptions to a separate file. The `Router` class doesn't seem to have interface to register exception. 

I'm happy to contribute if I am assisted a little bit. Thanks!!

**Comment by heitorlessa** [comment]
oh hey, seeing this only now as it was closed -- That's something else, that would be a feature request to add `exception_handler` to the `Router` class. It was an oversight. This issue was for `App` not `Router`.

@rajalokan if you've got the bandwidth, it'll need two changes (we need a feature request issue):

* [Add `exception_handler` method in the `Router`](https://github.com/aws-powertools/powertools-lambda-python/blob/4b90ed2577a8bcd592cf1bf237d5cb108a96192c/aws_lambda_powertools/event_handler/api_gateway.py#L1228)
* [Merge registered exception handlers from `Router` into `App`](https://github.com/aws-powertools/powertools-lambda-python/blob/4b90ed2577a8bcd592cf1bf237d5cb108a96192c/aws_lambda_powertools/event_handler/api_gateway.py#L1186) - it'd be a dict merge (`self._exception_handlers`)

**Comment by alecrevangelista** [comment]
Any update on this feature @heitorlessa  // @rajalokan ?

**Comment by leandrodamascena** [comment]
Reopening this issue as using `@router.exception_handler` still doesn't work.

Sending a PR in few minutes.

**Comment by leandrodamascena** [comment]
Thank you for commenting here and bringing this issue to our attention @alecrevangelista!
